[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore some long path
    '''server.key$''',
    '''client.key$''',
    '''ca.key$''',
  ]